/**
 * Widget config registry. Each widget defines:
 *   - default w/h for new instances
 *   - min/max w/h constraints for drag-resize
 *   - icon + iconColor for the library
 */

import {
  AlertTriangle,
  DollarSign,
  TrendingUp,
  RefreshCw,
  Zap,
  LineChart,
  Sparkles,
  Lightbulb,
  Users,
  Layers,
  PieChart,
  Globe,
  Activity,
  CalendarRange,
} from "lucide-react";
import type { SizeTier, WidgetConfig, WidgetType } from "./types";

export const WIDGET_CONFIGS: Record<WidgetType, WidgetConfig> = {
  kpi_revenue_at_risk: {
    title: "Revenue at Risk",
    description: "Predicted revenue loss from at-risk customers",
    category: "kpis",
    icon: AlertTriangle,
    iconColor: "red",
    defaultW: 3,
    defaultH: 3,
    minW: 2,
    maxW: 6,
    minH: 2,
    maxH: 4,
    allowMultiple: false,
  },
  kpi_total_revenue: {
    title: "Total Revenue",
    description: "Revenue over the last 30 days",
    category: "kpis",
    icon: DollarSign,
    iconColor: "green",
    defaultW: 3,
    defaultH: 3,
    minW: 2,
    maxW: 6,
    minH: 2,
    maxH: 4,
    allowMultiple: false,
  },
  kpi_predicted_clv: {
    title: "Predicted CLV",
    description: "365-day customer lifetime value forecast",
    category: "kpis",
    icon: TrendingUp,
    iconColor: "blue",
    defaultW: 3,
    defaultH: 3,
    minW: 2,
    maxW: 6,
    minH: 2,
    maxH: 4,
    allowMultiple: false,
  },
  kpi_repeat_rate: {
    title: "Repeat Rate",
    description: "Percentage of customers with multiple purchases",
    category: "kpis",
    icon: RefreshCw,
    iconColor: "amber",
    defaultW: 3,
    defaultH: 3,
    minW: 2,
    maxW: 6,
    minH: 2,
    maxH: 4,
    allowMultiple: false,
  },
  priority_bar: {
    title: "Today's Priority",
    description: "Top actions to take right now",
    category: "customers",
    icon: Zap,
    iconColor: "red",
    defaultW: 12,
    defaultH: 3,
    minW: 6,
    maxW: 12,
    minH: 2,
    maxH: 6,
    allowMultiple: false,
  },
  trend_chart: {
    title: "Revenue Trend",
    description: "Daily revenue over the last 30 days",
    category: "analytics",
    icon: LineChart,
    iconColor: "blue",
    defaultW: 12,
    defaultH: 4,
    minW: 6,
    maxW: 12,
    minH: 3,
    maxH: 6,
    allowMultiple: false,
  },
  dna_featured: {
    title: "Featured Customer DNA",
    description: "Your highest-impact at-risk customer",
    category: "customers",
    icon: Sparkles,
    iconColor: "pink",
    defaultW: 7,
    defaultH: 5,
    minW: 4,
    maxW: 12,
    minH: 4,
    maxH: 8,
    allowMultiple: false,
  },
  why_reasoning: {
    title: "Why We Recommend",
    description: "Reasoning behind featured recommendation",
    category: "customers",
    icon: Lightbulb,
    iconColor: "amber",
    defaultW: 5,
    defaultH: 5,
    minW: 4,
    maxW: 8,
    minH: 3,
    maxH: 8,
    allowMultiple: false,
  },
  at_risk_table: {
    title: "At-Risk Customers",
    description: "Top customers showing churn signals",
    category: "customers",
    icon: Users,
    iconColor: "coral",
    defaultW: 12,
    defaultH: 4,
    minW: 6,
    maxW: 12,
    minH: 3,
    maxH: 8,
    allowMultiple: false,
  },
  lifecycle_distribution: {
    title: "Lifecycle Distribution",
    description: "Where your customers are right now",
    category: "analytics",
    icon: Layers,
    iconColor: "purple",
    // 7 lifecycle stages — compact horizontal-row layout fits at h:5
    defaultW: 6,
    defaultH: 5,
    minW: 4,
    maxW: 12,
    minH: 4,
    maxH: 8,
    allowMultiple: false,
  },
  value_tier_donut: {
    title: "Value Tier Distribution",
    description: "Predicted CLV by tier",
    category: "analytics",
    icon: PieChart,
    iconColor: "green",
    defaultW: 6,
    defaultH: 4,
    minW: 3,
    maxW: 12,
    minH: 2,
    maxH: 6,
    allowMultiple: false,
  },
  geographic_spread: {
    title: "Geographic Spread",
    description: "Where your customers are located",
    category: "analytics",
    icon: Globe,
    iconColor: "coral",
    defaultW: 6,
    defaultH: 4,
    minW: 4,
    maxW: 12,
    minH: 3,
    maxH: 8,
    allowMultiple: false,
  },
  health_score_trend: {
    title: "Health Score Trend",
    description: "Average customer health over time",
    category: "analytics",
    icon: Activity,
    iconColor: "green",
    defaultW: 12,
    defaultH: 4,
    minW: 6,
    maxW: 12,
    minH: 3,
    maxH: 6,
    allowMultiple: false,
  },
  cohort_health: {
    title: "Cohort Health",
    description: "Retention by signup month",
    category: "analytics",
    icon: CalendarRange,
    iconColor: "amber",
    defaultW: 6,
    defaultH: 5,
    minW: 4,
    maxW: 12,
    minH: 4,
    maxH: 8,
    allowMultiple: false,
  },
  recent_activity: {
    title: "Recent Activity",
    description: "Latest customer events",
    category: "customers",
    icon: Activity,
    iconColor: "coral",
    defaultW: 6,
    defaultH: 5,
    minW: 4,
    maxW: 8,
    minH: 4,
    maxH: 8,
    allowMultiple: false,
  },
  anomalies_panel: {
    title: "Anomalies",
    description: "Seasonality-aware alerts",
    category: "analytics",
    icon: AlertTriangle,
    iconColor: "red",
    defaultW: 6,
    defaultH: 5,
    minW: 4,
    maxW: 12,
    minH: 4,
    maxH: 10,
    allowMultiple: false,
  },
};

/**
 * Legacy v1 size-tier → dims map. Used ONLY to migrate older saved layouts
 * (where widgets had `size: 'small'|'medium'|'large'` instead of explicit w/h).
 */
const LEGACY_TIER_DIMS: Record<
  WidgetType,
  Partial<Record<SizeTier, { w: number; h: number }>>
> = {
  kpi_revenue_at_risk: { small: { w: 3, h: 3 } },
  kpi_total_revenue: { small: { w: 3, h: 3 } },
  kpi_predicted_clv: { small: { w: 3, h: 3 } },
  kpi_repeat_rate: { small: { w: 3, h: 3 } },
  priority_bar: { large: { w: 12, h: 2 } },
  trend_chart: { medium: { w: 8, h: 4 }, large: { w: 12, h: 4 } },
  dna_featured: { medium: { w: 5, h: 5 }, large: { w: 7, h: 5 } },
  why_reasoning: { medium: { w: 5, h: 5 } },
  at_risk_table: { medium: { w: 8, h: 4 }, large: { w: 12, h: 4 } },
  lifecycle_distribution: { small: { w: 4, h: 3 }, medium: { w: 6, h: 3 } },
  value_tier_donut: { small: { w: 4, h: 3 }, medium: { w: 6, h: 3 } },
  geographic_spread: {},
  health_score_trend: {},
  cohort_health: {},
  recent_activity: {},
  anomalies_panel: {},
};

/**
 * Migrate one widget from the legacy `size` field to explicit `w`/`h`.
 * Returns it unchanged if it already has w/h.
 */
export function migrateLegacyWidget<
  T extends { type?: WidgetType; size?: SizeTier; w?: number; h?: number },
>(widget: T): T & { w: number; h: number } {
  if (typeof widget.w === "number" && typeof widget.h === "number") {
    return widget as T & { w: number; h: number };
  }
  const config = widget.type ? WIDGET_CONFIGS[widget.type] : null;
  if (widget.type && widget.size) {
    const dims = LEGACY_TIER_DIMS[widget.type]?.[widget.size];
    if (dims) return { ...widget, w: dims.w, h: dims.h };
  }
  return {
    ...widget,
    w: config?.defaultW ?? 3,
    h: config?.defaultH ?? 3,
  };
}
